module.exports = {
  content: ['content/**/*.md', 'layouts/**/*.html'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'fg-color': '#212121',
      'alt-bg-color': '#e0e0e0',
      'alt-fg-color': '#000',
      'darker-alt-bg-color': '#ccc',
      'font-highlight-color': '#ed4759',
      'font-highlight-bg-color': '#ededeb',
      'code-bg-color-light': '#f7f6f3',
      'gray-archives-meta': '#6C6C6C',
      'code-bg-color-dark': '#0e1116',
      'code-copy-button': '#e952a6',
      'bg-color-dark': '#212121',
      'fg-color-dark': '#dadada',
      'alt-bg-color-dark': '#424242',
      'alt-fg-color-dark': '#dadada',
      'lighter-alt-bg-color-dark': '#4f4f4f',
      'link-color-dark': '#42a5f5',
      'body-bg-dark': '#181a1b',
      'border-dark': '$gray-800',
      'body-color-dark': '$gray-300',
      'color-dark-cyan': '#84ebd9',
      'color-dark-blue': '#6ab0e5',
      'color-dark-blue-200': '#1565c0',
      'color-dark-purple': '#d35af7',
      'color-dark-yellow': '#fdec6d',
      'color-dark-pink': '#ed6d91',
      'color-dark-pink-200': '#dd556a',
      'color-dark-pink-300': '#e952a6',
      'color-dark-red': '#eb4344',
      'color-dark-orange': '#f1964f',
      'color-dark-code-bg': '#202020',
    },
    extend: {},
  },
  plugins: [],
}
